### ISSUE TITLE
Not clear which genesis files belong to which network

### ISSUE THREAD

**Issue by fedyiv** [sovrin-foundation/sovrin#299]
[Here](https://sovrin.org/overview/) is is mentioned that there are three Sovrin Networks:

    MainNet (prod)
    StageNet (pre-prod)
    BuilderNet (test)

But I can not find genesis files for those networks.

In sovrin github https://github.com/sovrin-foundation/sovrin/tree/master/sovrin

There are some genesis files but their names do not match with the nets above.

Where can I find the proper genesis files or mapping between the names?

**Comment by WadeBarnes** [comment]
Genesis Files:
- [MainNet](https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_live_genesis)
- [StagingNet](https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_sandbox_genesis)
- [BuilderNet](https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis)

**Comment by fedyiv** [comment]
Thank you! Do you think those links should be added at some place in the documentation in scope of this issue or it should be closed now?

**Comment by WadeBarnes** [comment]
@fedyiv, Apologies for the slow reply.  Please have a look at the linked PR documenting the genesis file locations.

**Comment by fedyiv** [comment]
@WadeBarnes that looks great! Thank you!
