### ISSUE TITLE
Create the a ledger rule script that is based on the current settings, copying the approach of CANdy

### ISSUE THREAD

**Issue by swcurran** [sovrin-foundation/sovrin#323]

**Comment by WadeBarnes** [comment]
Rules being added here; https://github.com/sovrin-foundation/sovrin/pull/344

**Comment by WadeBarnes** [comment]
Rules for all three networks have been added to the PR and are ready for review.

**Comment by swcurran** [comment]
Wade — are the rules scripts that you posted the “as of today”, or have you already applied the planned changes and we are reviewing that?  I’m assuming the first, but please let us know.

Also, how did you create the scripts?  Is there anything general purpose that can be put into the Indy Node repo?  A script and/or instructions on how to create the script?  It seems to be very valuable.

Thanks!

**Comment by WadeBarnes** [comment]
@swcurran, The rules are "as of today" for each network.  I figured this would be the best way to proceed since all changes can then be tracked in source control.  These scripts were created manually, using the ones from the CANdy repo as a base.

**Comment by swcurran** [comment]
Sounds good.  Is it worth the effort to create and check in the rules for a default Indy network?  Would be useful if not that painful to create.

Is there a way to script an audit of this form of the rules against what is generated from the Indy transaction call?  Or from a locally run script on a node?  It seems incredibly valuable to have some tools around managing the rules that are better than what was created back in the day.

**Comment by WadeBarnes** [comment]
Creating a script with the default rules would not be difficult.

Yes, it's possible to automate an audit, or even auto-gen the script.  It will take a while to develop and test though.  It was just faster to hand bomb this first set.
