### ISSUE TITLE
Add columns for the following ratings for Stewards “Outages”, “Responsiveness”, “Payments” and a “Ratings Notes” column

### ISSUE THREAD

**Issue by swcurran** [sovrin-foundation/sovrin#328]

**Comment by swcurran** [comment]
Scores will be 1-5 (Worst to Best).  Initially, set them all to “5”.  As people make changes, they will add notes to indicate why they are making a change.  The “Ratings Notes” can be a single text field, but if there is a technique in AirTable to make it a log (perhaps in another table?) capturing — note, author, date time — that would be nice.  Only if it is easy :-)

**Comment by ConnorBarnes88** [comment]
What tab do you want the columns added to?

**Comment by swcurran** [comment]
I think the same table as the rest of the Stewards info.  I can’t see if going elsewhere, but open to ideas.

**Comment by ConnorBarnes88** [comment]
Still a work in progress, but I added a way we can do the ratings with stars.  Check Steward nodes and scroll to the end column named outages. See if you like it

**Comment by ConnorBarnes88** [comment]
I believe I more or less have something together, Stephen if you could to take a look at it to see if you like it.  If you have any questions on how I've put things together or changes please let me know.
