### ISSUE TITLE
Check Sovrin Foundation github for references to “StagingNet” that should be changed

### ISSUE THREAD

**Issue by swcurran** [sovrin-foundation/sovrin#331]

**Comment by swcurran** [comment]
I can do the updates if that is appropriate. Just do a brief check to see what needs to be done.

**Comment by KoleBarnes** [comment]
- [TAA/README.md](https://github.com/sovrin-foundation/sovrin/blob/a09c48b1d917ffc9ea173d118877dc95da83c7ee/TAA/README.md)
  - Update (I'll change this)
  - Edit: PR https://github.com/sovrin-foundation/sovrin/pull/346
- [/README.md](https://github.com/sovrin-foundation/sovrin/blob/31bba83edc6edbd884bbddaf90201522ff61c2f8/README.md)
  - Update (I'll change this)
  - Edit: PR https://github.com/sovrin-foundation/sovrin/pull/346
- [installer/network_pkg_versions](https://github.com/sovrin-foundation/steward-tools/blob/4b746d7d3a3ccd5981c9c984df39dab44258c2fc/installer/network_pkg_versions)
  - Old records. No point in updating
- [selfserve/static/endorser.html](https://github.com/sovrin-foundation/community-tools/blob/602974ad181fc478dc6c201fd82fff2c72ad9a42/selfserve/static/endorser.html)
  - This is for selfserve and we are not using it anymore. No point in updating.
- [selfserve/main_selfserve/main.py](https://github.com/sovrin-foundation/community-tools/blob/80b8e10c9a4bfea8b3376506d4286a752e986b6d/selfserve/main_selfserve/main.py)
  - This is for selfserve and we are not using it anymore. No point in updating.
- [/selfserve_load.py](https://github.com/sovrin-foundation/community-tools/blob/80b8e10c9a4bfea8b3376506d4286a752e986b6d/selfserve_load.py)
  - This is for selfserve and we are not using it anymore. No point in updating.
- [selfserve/main_selfserve/nym.py](https://github.com/sovrin-foundation/community-tools/blob/c2a57b46a159a9fa67ad2f6eb7bc3d5ea2ab16d5/selfserve/main_selfserve/nym.py)
  - This is for selfserve and we are not using it anymore. No point in updating.

**Comment by WadeBarnes** [comment]
Done
