### ISSUE TITLE
DID Method spec doesn't render properly

### ISSUE THREAD

**Issue by kimdhamilton** [sovrin-foundation/sovrin#87]
The link from the DID method registry is https://github.com/w3c-ccg/sovrin/blob/master/spec/did-method-spec-template.html. To view it properly, I forked this repo; you can see the rendered version here: 
https://w3c-ccg.github.io/sovrin/spec/did-method-spec-template.html

**Comment by mikelodder7** [comment]
See https://github.com/w3c-ccg/did-method-registry/pull/8

The link is https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html

**Comment by kimdhamilton** [comment]
Thanks @mikelodder7!
